### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Akalinsky/simplewebapp2_2-15#1]
It looks like I'm seeing some [HTML errors thrown by your app](http://validator.w3.org/check?uri=https%3A%2F%2Fsimplewebapp1-26.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Can you fix these?

Also, the following notes below don't need to be updated in this project, but you should keep them in mind for future projects.

### Inconsistent indentation

I do notice some inconsistent indentation in some files, which I'd like you to try to clean up in future projects. Let me know if you're not sure what I mean or how you'd fix it.

### Unused `index1.html` (and others)

It looks like there are some unused files in your views folder. Since they're no longer needed, it's best to just delete them to keep our project from becoming cluttered.

If you you did delete them locally and are surprised that they're still on GitHub, then try running this line before your next commit:

``` bash
git add -A .
```

That will add not only file additions and modifications, but also file deletions. I know, it's strange that you need a special parameter for this, but you do.

### Filename comments

Just so you know for future reference, you don't actually need comments such as `# Gemfile` and `# app.rb` in your files. I just include them in code examples sometimes so you know which file the code would appear in.

**Comment by Akalinsky** [comment]
I believe I have fixed the validation issues. I spammed refresh a bunch of times because it appears to be pulling one of the 3 pages and it was very inconsistent with showing which had issues. Let me know if there was still any that I missed!

https://simplewebapp1-26.herokuapp.com/

**Comment by chrisvfritz** [comment]
:+1: Much better!
